### ISSUE TITLE
Write notes on California transparency laws 

### ISSUE THREAD

**Issue by fdhidalgo** [fdhidalgo/govt_transparency#5]

**Comment by jennyyu1** [comment]
### California Transparency Notes

 **Proposition 42: California Compliance of Local Agencies with Public Act**
- all local governments and agencies must comply with the California Public Records Act (CPRA) and the Ralph M. Brown Act (Brown Act)

- California Public Records Act (CPRA):
  - Public records are open to inspection at all times during the office hours of state/local agencies. 
  - Every person has a right to inspect any public record
  - Agencies are required to establish written guidelines for public access to their documents and post these guidelines at their offices

- California Ralph M. Brown Act (Brown Act)
  - Requires legislative bodies to provide notice of the time and place for holding regular meetings
  - Requires all meetings of a legislative body to be public and open
  - Permits all persons to attend meetings of a local legislative body unless a closed session is authorized

- Local governments are responsible for the costs associated with compliance with access laws

**Economics Interest Disclosure** 

- Types of economics interests that must be disclosed: sources of income, personal finances, real property, investments, business employment/management, business-owned property, loans, gifts

**Exemptions to Public Disclosure of Records**

- "pending litigation" exemption: exempts from disclosure documents prepared in support of ongoing litigation

- "drafts" exemption: exempts from disclosure preliminary drafts, notes or other interagency or
intra-agency memoranda not retained in the agency’s ordinary course of business

- "personal privacy" exemption: exempts from disclosure personnel files, medical records or other
such files, the disclosure of which would constitute an unwarranted invasion of personal privacy

**Comment by fdhidalgo** [comment]
Great start! 

I've moved this to a document here: background_research/state_laws/CA_transparency_notes.md

Add to it and edit it there (as opposed to this comment).

As you add to this, one thing to look for in particular is regulations mandating disclosures on government websites.

**Comment by fdhidalgo** [comment]
This article looks like it has some good information:
https://www.revealnews.org/article-legacy/californias-public-payroll-database-falls-short-on-transparency/

Also chapter 4 looks relevant:
https://www.ca-ilg.org/sites/main/files/ethics_booklet_full_v4.pdf

**Comment by jennyyu1** [comment]
sounds good thanks!

**Comment by fdhidalgo** [comment]
Regarding this "Enterprise System Catalog", is this a website that the public can see?

**Comment by jennyyu1** [comment]
I added the link to details about the catalog of Enterprise Systems: https://www.scag.ca.gov/about/Documents/Enterprise_System_Catalog.pdf. This chart seems to link to many other data bases and sources that are accessible to all.

**Comment by fdhidalgo** [comment]
One additional question I have: is there any information on what specific financial transactions are required to be reported? At what level of detail?

**Comment by jennyyu1** [comment]
I just added a list of items that should be included in the Financial Transactions Report. This data is published in an open data base on the CA State Controller's website, though I did not find anything explicitly stating it should be published on the local website.

**Comment by fdhidalgo** [comment]
Ok, thanks. Will close this issue now.
