### ISSUE TITLE
Write notes on North Carolina transparency laws

### ISSUE THREAD

**Issue by fdhidalgo** [fdhidalgo/govt_transparency#6]

**Comment by fdhidalgo** [comment]
Can you find out when the NC Open meetings law started mandating meeting schedule postings on the website?

**Comment by KarlaMagana101** [comment]
§ 143-318.12, Public notice of official meetings section, which includes the mandate for schedule postings on their website, was first added in 1979 and most recently amended in 2009 (I added this to the notes)

**Comment by fdhidalgo** [comment]
Great job.
