### ISSUE TITLE
Write notes on Georgia transparency laws

### ISSUE THREAD

**Issue by fdhidalgo** [fdhidalgo/govt_transparency#8]

**Comment by fdhidalgo** [comment]
You wrote "Agencies are required to post meeting information and schedules on its website if it has one". Can you find the specific law or regulation that states this? Also, can you find when this regulation was started?

**Comment by BlueAcornTech** [comment]
It took me a while searching through specific laws, but I managed to find information pertaining to digital regulations of public record requests. All of that research is uploaded under the header "Digital Requirements in Georgia Sunshine Laws"

**Comment by fdhidalgo** [comment]
Great, thanks
